---
title: "Assignment 4"
author: "Pearl L. Dlamini"
date: "2023-01-17"
output: html_document
---
### Question 1
```{r}
n_dims <- c(3)
print(n_dims)

# a.
v <- seq(1:n_dims^2)
print(v)

# b. 
sample(v, size=n_dims^2)

# c.
m <- matrix(data = v, nrow=n_dims)
print(m)

# d.
tm <- t(m)
print(tm)

# e. i, mean and sum of first row
mean(m[1,])
sum(m[1,])

# e. ii, mean and sum of last row
mean(m[3,])
sum(m[3,])


```
## Assignment 5 (4 cont.)
### Question 2
```{r}
# a.
my_matrix <- matrix(runif(n=16), nrow=4)

v <- (runif(n=100, min=10, max=100))
my_logical <- (v < 50)

my_letters <- (sample(letters, 26))

my_list <- list(my_matrix, my_logical, my_letters)
print (my_list)

# b.
my_list2 <- list(my_matrix[2,2], my_logical[2], my_letters [2])
print(my_list2)

# c.
typeof(my_matrix[2,2])

typeof(my_logical[2])

typeof(my_letters[2])

# d.
vector2 <- c(my_matrix[2,2], my_logical[2], my_letters [2])
print(vector2)

# e.
typeof(vector2)

```
### Question 3
```{r}
# a.
my_unifs <- runif(26, min=0, max=10)
my_letters2 <- sample(LETTERS, 26)
d_Frame <- data.frame(my_unifs, my_letters2)
print(d_Frame)

# b.
sample(my_unifs, 4)
d_Frame[sample(1:nrow(d_Frame), 4), 1] <- NA
print(d_Frame)

# c.
which(is.na(d_Frame))

# d.
orderedd_Frame <- d_Frame[order(d_Frame$my_letters2),]
print(orderedd_Frame)

# e.
mean(my_unifs)

#f 
colnames(d_Frame)[colnames(d_Frame) == "my_letters2"] <- "my_LETTERS"
print(colnames(d_Frame))
```


```{r}
