---
title: "Assignment 3"
author: "Pearl L. Dlamini"
date: "2023-01-12"
output: html_document
---


### Question 1.
```{r}
x = 1.1
a = 2.2
b = 3.3

# a.
z = x^a^b
print(z)

# b.
z = (x^a)^b
print(z)

# c.
z = 3*x^3 + 2*x^2 +1 
print(z)
```
### Question 2.
```{r}
# a.
c(seq(from=1,to=8), seq(from=7,to=1))

# b.
z <- rep(seq(from=1, to=5), (1:5))
print(z)

# c.
z <- rep(seq(from=5, to=1), (1:5))
print(z)
```
### Question 3.
```{r}
queue <- c("sheep","fox","owl","ant")
print(queue)

# a. the serpent arrives
queue <- c(queue[1:4], "serpent")
print(queue)

# b. the sheep enters the ark
queue <- c(queue[2:5])
print(queue)

# c. the donkey arrives and talks his way to the front of the line
queue <- c("donkey", queue[1:4])
print(queue)

# d. the serpent gets impatient and leaves
queue <- c(queue[1:4])
print(queue)

# e. the aphid arrives and the ant invites him to cut in line (hint: check out the append function).
queue <- c(queue[1:3], "aphid", queue[4])
print(queue)

# f. Finally, determine the position of the aphid in the line (hint: use the which function).
which (queue == "aphid")
```