---
title: "Weekly Assignment 2"
author: "Pearl L. Dlamini"
date: "2023-01-22"
output: html_document
---
### Question 1
```{r}
# Set default function first
set.seed(123)
myFunc <- function(mean1=10, sd1=1.5, mean2=45, sd2=2, n=25){
  Type <- rep(c("Control", "Treatment"), each=25)  
  Value <- c(rnorm(n, mean=mean1, sd=sd1), rnorm(n, mean=mean2, sd=sd2))
  d_Frame <- data.frame(Type, Value)
  return(d_Frame)
}
```
### Question 2
```{r}
data_Frame <- myFunc()
head(data_Frame)
```
### Question 3
```{r}
ANOVA <- aov(Value~Type, data = myFunc())
summary(ANOVA)
```
### Question 4
```{r}
# Function name: ANOVA_2
#Input: data frame with two columns
# Output: p_value
ANOVA_2 <- function(df = NULL){
  if (is.null(df)){
    df <- data_Frame
  }
  
  if (length(df)!=2) {
    return("Function failure: data frame must have two columns")
  }
  
   #data_frame <- data_Frame
   colnames(df) <- c("Explanatory","Response")
   my_aov <- aov(Response~Explanatory, data = df)
   anova_summary <- summary(my_aov)
   my_out <- c(anova_summary[[1]]["Explanatory", "Pr(>F)"])
   return(my_out)
}
ANOVA_2()

ANOVA_2(myFunc())
```

